[package]
name = "rweb_helper"
version = "0.3.4"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.6"
rweb = {version="0.14", features=["openapi"]}
serde = { version="1.0", features=["derive"] }
rweb_helper_macro = {path = "./rweb_helper_macro"}

[dev-dependencies]
serde_json = "1.0"
