[package]
name = "rweb_helper"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.6"
rweb = {version="0.12", features=["openapi"]}
serde = { version="1.0", features=["derive"] }
