[package]
name = "rweb_helper_macro"
version = "0.2.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version="1.0", features=["full", "printing", "extra-traits"]}
quote = "1.0"
rweb-macros = "0.11"
rweb_base = {path="../rweb_base"}

[lib]
proc-macro = true
